#!/bin/bash
#!/bin/bash
fxbin="$HOME/firefox-nightly/firefox"
profile="$HOME/.mozilla/firefox/eq7adpzs.nightly"
bzdeckurl='https://www.bzdeck.com'

echo $bzdeckrul='https://www.bzdeck.com'
echo $fxbin -Profile $profile --no-remote $bzdeckurl
$fxbin -Profile $profile --no-remote $bzdeckurl

