#!/bin/bash
# TODO:
# Open current commit
# Create github repo and set it as remote origin

BROWSER="firefox"

if [ ! $(git rev-parse --is-inside-work-tree) ]
then

  $BROWSER "https://github.com"
  echo "https://github.com"

else # If in a github repo

  CURR_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
  ORIGIN_URL="$(git config --get remote.origin.url | sed 's/git@/https:\/\//g' | sed 's/com:/com\//g' | sed 's/.git$//g')"

  case "$1" in 
  pr) 
    PR_URL="$ORIGIN_URL/compare/$CURR_BRANCH"
    $BROWSER $PR_URL
    echo $PR_URL
    ;;
  *) 
    case "$ORIGIN_URL" in 
    "")
      $BROWSER "https://github.com/new"
      echo "https://github.com/new"
      ;;
    *)
      BRANCH_URL="$ORIGIN_URL/tree/$CURR_BRANCH"
      $BROWSER $BRANCH_URL
      echo $BRANCH_URL
      ;;
    esac
    ;;
  esac
fi
