#!/bin/bash
# Run the command when a hotkey is pressed
# Usage: onhotkey [your command]
# 
# Dependencies: xbindkeys

hotkey=F9
xbindkeysrc='/tmp/xbindkeysrc'

#last_run=$(date +%s)
runcmd() {
  #this_run=$(date +%s)
  #time_waited=$((this_run - last_run))
  #if [ $time_waited -gt 1  ] #debounce for 1 second
  #then
    echo ""
    echo ">>>>>" $(date) ">>>>>"
    #$@
    ringring $@
    echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
    #last_run=$this_run
  #fi

}

mainloop() {
  xbindkeys -n -f $xbindkeysrc| \
     while read line ; do
       echo "$line" | grep -q "hotkey"
       if [ $? = 0  ]
       then
         runcmd $@
       fi
     done
}

createXbindkeysrc() {
  echo "\"echo hotkey\"" > $xbindkeysrc
  echo "  $hotkey" >> $xbindkeysrc
}

createXbindkeysrc
mainloop $@
